x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    environment:
      BOT_TOKEN: 6686728746:AAEVM6Wp0ptZR81uzMsWt7WIpSXAyYWM3pc
      API_ID: 29228879
      API_HASH: f8c420d7f974ef0a2bc23a9a4a0dc859
      CHANNELS: -1001996814616
      ADMINS: 5809081123
      LOG_CHANNEL: -1002021088905
      DATABASE_NAME: Cluster0
      DATABASE_URI: mongodb+srv://perera51:perera51@cluster0.c5kzo5m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      COLLECTION_NAME: adg_movies
      AUTH_CHANNEL: -1001996814616
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
